name: native_android_path
description: "A Flutter plugin that provides access to various storage paths on Android devices."
version: 0.0.3
homepage:

environment:
  sdk: ^3.8.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.example.native_android_path
        pluginClass: NativeAndroidPathPlugin

  
